# Generated by Django 5.0.7 on 2024-07-30 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mainsrc', models.CharField(max_length=200)),
                ('width', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('scalX', models.CharField(max_length=200)),
                ('scalY', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('opacity', models.CharField(max_length=200)),
                ('rotation', models.CharField(max_length=200)),
                ('anchorPoint', models.CharField(max_length=200)),
                ('isLocked', models.CharField(max_length=200)),
                ('show', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('font', models.CharField(max_length=200)),
                ('inPoin', models.CharField(max_length=200)),
                ('outPoint', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_path', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('creatd_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompositModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composit_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('startTime', models.CharField(max_length=200)),
                ('frameRate', models.CharField(max_length=200)),
                ('width', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('workAreaStartTime', models.CharField(max_length=200)),
                ('workAreaEndTime', models.CharField(max_length=200)),
                ('opacity', models.CharField(max_length=200)),
                ('isLocked', models.CharField(max_length=200)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_composit', to='canvasmanager.projectmodel')),
            ],
        ),
    ]
