# Generated by Django 5.0.7 on 2024-08-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvasmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layermodel',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
