# Generated by Django 5.0.7 on 2024-08-01 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvasmanager', '0003_alter_layermodel_anchorpoint_alter_layermodel_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layermodel',
            name='compositid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_composit_layer', to='canvasmanager.compositmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layermodel',
            name='projectid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='project_layer', to='canvasmanager.projectmodel'),
            preserve_default=False,
        ),
    ]
