# Generated by Django 5.0.7 on 2024-09-16 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorymanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composit_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('startTime', models.CharField(max_length=200)),
                ('frameRate', models.CharField(max_length=200)),
                ('width', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('workAreaStartTime', models.CharField(max_length=200)),
                ('workAreaEndTime', models.CharField(max_length=200)),
                ('opacity', models.CharField(max_length=200)),
                ('isLocked', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('template_path', models.CharField(max_length=200)),
                ('template_thumb', models.ImageField(default=None, upload_to='template_thumbs/')),
                ('template_video', models.FileField(default=None, upload_to='template_thumbs/')),
                ('status', models.BooleanField(default=True)),
                ('creatd_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Template_category', to='categorymanager.categorymodel')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Template_subcategory', to='categorymanager.subcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='LayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mainsrc', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='uploads/')),
                ('width', models.CharField(blank=True, max_length=200, null=True)),
                ('height', models.CharField(blank=True, max_length=200, null=True)),
                ('scalX', models.CharField(blank=True, max_length=200, null=True)),
                ('scalY', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('opacity', models.CharField(blank=True, max_length=200, null=True)),
                ('rotation', models.CharField(blank=True, max_length=200, null=True)),
                ('anchorPoint', models.CharField(blank=True, max_length=200, null=True)),
                ('isLocked', models.CharField(blank=True, max_length=200, null=True)),
                ('show', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('font', models.CharField(blank=True, max_length=200, null=True)),
                ('inPoin', models.CharField(blank=True, max_length=200, null=True)),
                ('outPoint', models.CharField(blank=True, max_length=200, null=True)),
                ('compositid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_composit_layer', to='templatemanager.compositmodel')),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_layer', to='templatemanager.templatemodel')),
            ],
        ),
        migrations.AddField(
            model_name='compositmodel',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_composit', to='templatemanager.templatemodel'),
        ),
    ]
