# Generated by Django 5.0.7 on 2024-09-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanager', '0002_subcategorymodel_image_thumbnail_and_more'),
        ('templatemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemodel',
            name='created_by',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Template_subcategory', to='categorymanager.subcategorymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Template_category', to='categorymanager.categorymodel'),
        ),
    ]
