# Generated by Django 5.0.7 on 2024-09-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storemodel',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
