# Generated by Django 5.0.7 on 2024-09-16 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templatemanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templatemanager.templatemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreditsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTemplatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templaate_state', models.CharField(choices=[('Edited', 'Edited'), ('Standed', 'Standed')], default='Edited', max_length=200)),
                ('order_id', models.CharField(default=None, max_length=200)),
                ('main_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templatemanager.templatemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTemplatesLayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mainsrc', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='uploads/')),
                ('width', models.CharField(blank=True, max_length=200, null=True)),
                ('height', models.CharField(blank=True, max_length=200, null=True)),
                ('scalX', models.CharField(blank=True, max_length=200, null=True)),
                ('scalY', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('opacity', models.CharField(blank=True, max_length=200, null=True)),
                ('rotation', models.CharField(blank=True, max_length=200, null=True)),
                ('anchorPoint', models.CharField(blank=True, max_length=200, null=True)),
                ('isLocked', models.CharField(blank=True, max_length=200, null=True)),
                ('show', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('font', models.CharField(blank=True, max_length=200, null=True)),
                ('inPoin', models.CharField(blank=True, max_length=200, null=True)),
                ('outPoint', models.CharField(blank=True, max_length=200, null=True)),
                ('main_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templatemanager.templatemodel')),
                ('UserTemplatesCompositId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userproductsmanager.usertemplatesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserTemplatesComposModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composit_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('startTime', models.CharField(max_length=200)),
                ('frameRate', models.CharField(max_length=200)),
                ('width', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('workAreaStartTime', models.CharField(max_length=200)),
                ('workAreaEndTime', models.CharField(max_length=200)),
                ('opacity', models.CharField(max_length=200)),
                ('isLocked', models.CharField(max_length=200)),
                ('main_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templatemanager.templatemodel')),
                ('template_order_modelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userproductsmanager.usertemplatesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WishListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templatemanager.templatemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
