# Generated by Django 5.0.7 on 2024-09-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='small_thumbnail',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
