# Generated by Django 5.0.7 on 2024-09-14 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0004_rolesmodel_user_delete_usermanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usersroles', to='accountmanager.rolesmodel'),
        ),
    ]
